version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s  # check every 10 seconds
      timeout: 5s    # each check can take up to 5 seconds
      retries: 5

  fast_api:
    build: .
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy    # wait until db is healthy
    env_file:
      - .env
    
